#!/usr/bin/env bash

ls source
ls ~/.ssh
git --version
chmod 400 ./source/id_rsa
cp ./source/config ~/.ssh/config
git clone git@github.com:ucsd-cse12-w17/${ASSIGNMENT_TITLE}-grading.git
rm ./source/id_rsa
bash ${ASSIGNMENT_TITLE}-grading/ucsd-cse12-${ASSIGNMENT_TITLE}-grading/grade
